AppDaemon:
  cert_verify: False
  disable_apps: 1
  logfile: STDOUT
  errorfile: STDERR
  threads: 10
  app_dir: /config/hadaemon/apps
HASS:
#  ha_url: http://172.17.0.1:8123
  ha_url: http://192.168.1.254:8123
#  ha_key: !secret http_password
  ha_key: Mercury1
HADashboard:
  dash_url: http://192.168.1.254:3030
  dash_dir: /config/hadaemon/dashboards
#  dash_password: !secret dash_password
  dash_password: Mercury1
