
# Use this file to store secrets like usernames and passwords.
# Learn more at https://home-assistant.io/docs/configuration/secrets/
http_password: Mercury1
nest_id: 5c78bb56-0008-4482-961d-6468b17bb544
nest_secret: uxpAqWQnnYAWaD8Dg2rl8hRMJ
openweathermap_api_key: 0dff306dd3131463771638fa3b29c4f5
myq_user: steve.horvath@gmail.com
myq_pass: Mercury1
wunderground_api_key: c7f352fdadc73d0c
dash_password: Mercury1